### ISSUE TITLE
block error when create a custom island!

### ISSUE THREAD

**Issue by Milan09NL** [tastybento/askyblockIssues#935]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
spigot 1.12.2
**Plugin version:**
V3.0.9.4
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
V3.0.9.3
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
I create a own island and now i always get a block error.

Could not parse item [BRICK_BLOCK] in schematic - skipping!
[21:17:57 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.BRICK_BLOCK
[21:17:57 WARN]:        at java.lang.Enum.valueOf(Unknown Source)
[21:17:57 WARN]:        at org.bukkit.Material.valueOf(Material.java:1)
[21:17:57 WARN]:        at com.wasteofplastic.askyblock.schematics.IslandBlock.setChest(IslandBlock.java:499)
[21:17:57 WARN]:        at com.wasteofplastic.askyblock.schematics.Schematic.prePasteSchematic(Schematic.java:1199)
[21:17:57 WARN]:        at com.wasteofplastic.askyblock.schematics.Schematic.<init>(Schematic.java:645)
[21:17:57 WARN]:        at com.wasteofplastic.askyblock.commands.IslandCmd.loadSchematics(IslandCmd.java:260)
[21:17:57 WARN]:        at com.wasteofplastic.askyblock.commands.IslandCmd.<init>(IslandCmd.java:134)
[21:17:57 WARN]:        at com.wasteofplastic.askyblock.ASkyBlock.onEnable(ASkyBlock.java:358)
[21:17:57 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[21:17:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[21:17:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[21:17:57 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
[21:17:57 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
[21:17:57 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
[21:17:57 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[21:17:57 WARN]:        at java.lang.Thread.run(Unknown Source)

**What do you think should happen?**
any kind of block is not supported for the askyblock plugin
**Steps to make this happen**

1. idk
2. idk
3. idk

**What do you think should happen?**
update to 1.12.2 version

**Comment by tastybento** [comment]
The schematic was made with a plugin that defined a material called "BRICK_BLOCK". There is no **BRICK_BLOCK** in Bukkit 1.12.2. 

Sometimes, schematic plugins use non-standard or old material names and ASkyBlock tries to catch some of them but it can't catch them all, sorry. I recommend you redo your schematic in your server using a different schematic plugin.
